global:
    - CC_TEST_REPORTER_ID=b1567a7ea511a013af2b33cac1869186a39b1c9869acdfe3c3fe790d49b34b7f
language: node_js
node_js:
  - node
install:
- npm install -q --no-color --no-progress
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm install -g jest
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT